// THIS FILE IS AUTOMATICALLY GENERATED IN:
//
//   build-utils/update-file-index.js
//
// YOU SHOULD NEVER UPDATE THIS FILE DIRECTLY

import RemoteView from './RemoteView.vue'

// Export components individually
export { RemoteView }

// What should happen if the user installs the library as a plugin
function install(Vue) {
  Vue.component('RemoteView', RemoteView)
}

// Export the library as a plugin
export default { install: install }
